app = "fullstack-bun"
primary_region = "bos"

[[services]]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    type = "connections"
    soft_limit = 500
  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8080
  [[services.http_checks]]
    grace_period = "10s"
    interval = "60s"
    timeout = "5s"
    method = "GET"
    path = "/health"

[[services]]
  internal_port = 8081
  processes = ["app"]
  protocol = "tcp"
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8081

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
